- name: install go
  package:
    name: '{{ cmd_utils_go_package }}'
    state: latest
  become: '{{ true if ansible_os_family != "Darwin" else false }}'

- name: Cloning fzf repository
  git:
    repo: '{{ cmd_utils_fzf_repo_path }}'
    dest: '{{ cmd_utils_fzf_install_path }}'
    depth: 1

- name: Install fzf
  shell: ./install --completion --no-update-rc
  args:
    chdir: '{{ cmd_utils_fzf_install_path }}'
