# Configure GIT
- name: Use VIM as git core tool
  git_config:
    name: core.editor
    value: vim
    scope: global

- name: Use VIM as git diff-tool
  git_config:
    name: diff.tool
    value: vimdiff
    scope: global

- name: Disable prompt when diffing in git
  git_config:
    name: difftool.prompt
    value: false
    scope: global

- name: Autosetup of remote branches
  git_config:
    name: push.autoSetupRemote
    value: true
    scope: global

- name: Use VIM as git merge-tool
  git_config:
    name: merge.tool
    value: vimdiff
    scope: global

- name: Git push only current
  git_config:
    name: push.default
    value: upstream
    scope: global

- name: Set alias for gitv
  lineinfile:
    path: "{{ cmd_utils_alias_file }}"
    line: "alias gitv='git log --all --branches --graph --oneline --decorate'"
    create: yes

- name: Set alias git commit
  lineinfile:
    path: "{{ cmd_utils_alias_file }}"
    line: "alias gitcm='git commit -m'"
    create: yes

- name: Set alias git add
  lineinfile:
    path: "{{ cmd_utils_alias_file }}"
    line: "alias gita='git add'"
    create: yes


- name: Copy gitignore
  copy:
    src: gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
