- name: Install jrnl
  pip:
    name: jrnl
    executable: pip3
    extra_args: --upgrade
  become: true

- name: Store path to jrnl binary
  shell: which jrnl
  register: cmd_utils_jrnl_binary_which

- set_fact:
    cmd_utils_jrnl_binary: "{{ cmd_utils_jrnl_binary_which.stdout }}"
 
- name: Set alias for jrnl
  lineinfile:
    path: "{{ cmd_utils_alias_file }}"
    line: "alias jrnl=' {{ cmd_utils_jrnl_binary }}'"
    create: yes

- name: Copy jrnl config
  template:
    src: jrnl_config.j2
    dest: "{{ cmd_utils_jrnl_config_file }}"
