- name: Install jrnl
  pip:
    name: jrnl
    executable: pip3
    extra_args: --upgrade
  become: true

 # Important: Note the whitespace before the alias. That ensures that
 # jrnl entries will not show up in history!
 - name: Set alias for jrnl
   lineinfile:
     path: "{{ cmd_utils_alias_file }}"
     line: "alias jrnl=' /usr/bin/jrnl'"
     create: yes
