- name: Configure git
  include_tasks: git.yml

- name: Install and configure zsh
  include_tasks: zsh.yml

- name: Install and configure fzf
  include_tasks: fzf.yml

- name: Install and configure tmux
  include_tasks: tmux.yml

- name: Install and configure jrnl
  include_tasks: jrnl.yml

- name: Set alias ll
  lineinfile:
    path: "{{ cmd_utils_alias_file }}"
    line: "alias ll='ls -lah'"
    create: yes
