- name: install tmux
  package:
    name: tmux
    state: latest
  become: '{{ true if ansible_os_family != "Darwin" else false }}'

- name: Copy tmux.conf
  template:
    src: tmux.conf.j2
    dest: "{{ cmd_utils_tmux_config_file }}"

# Export TERM variable. This is needed for TMUX to display colors in
# VIM correctly
- name: Export color environment variable
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    line: TERM=xterm-256color
    create: true

- name: Make sure that .ssh dir exists
  file:
    path: "{{ cmd_utils_ssh_dir }}"
    state: directory

- name: Take care of ssh-agents under tmux
  blockinfile:
    path: "{{ cmd_utils_ssh_rc_file }}"
    marker: "# BLOCK MANAGED BY ANSIBLE"
    create: yes
    content: |
      # Fix SSH auth socket location so agent forwarding works with tmux
      if test "$SSH_AUTH_SOCK" ; then
        ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
      fi
