- name: install zsh
  package:
    name: zsh
    state: latest
  become: '{{ true if ansible_os_family != "Darwin" else false }}'

- name: Install virtualenvwrapper
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --upgrade
  become: true
  with_items: 
    - virtualenv
    - virtualenvwrapper

- name: Store path to zsh binary
  shell: which zsh
  register: cmd_utils_zsh_binary_which

- set_fact:
    cmd_utils_zsh_binary: "{{ cmd_utils_zsh_binary_which.stdout }}"
 
- name: Make zsh default shell
  user: name={{ ansible_user_id }} shell={{ cmd_utils_zsh_binary }}
  become: true

- name: Clone oh-my-zsh
  git:
    repo: "{{ cmd_utils_omz_git_repo }}"
    dest: "{{ cmd_utils_omz_path }}"

- name: Clone zsh-autosuggestions
  git:
    repo: "{{ cmd_utils_omz_zsh_suggestions_repo }}"
    dest: "{{ cmd_utils_omz_zsh_suggestions_path }}"

- name: Copy zshrc
  template:
    src: zshrc.j2
    dest: "{{ cmd_utils_zsh_rc }}"

- name: Copy fzf helpers
  template:
    src: fzf_helpers.j2
    dest: "{{ cmd_utils_fzf_helpers }}"

- name: Copy ssh helpers
  template:
    src: ssh_helpers.j2
    dest: "{{ cmd_utils_ssh_helpers }}"

- name: Copy zsh dircolors
  copy:
    src: dircolors
    dest: "{{ cmd_utils_zsh_dircolors }}"
